name 'mytestsite'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures mytestsite'
long_description 'Installs/Configures mytestsite'
version '0.1.0'

depends 'artifact'
depends 'apache2'
depends 'zipfile'
depends 'zip'
