name 'testusers'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures testusers'
long_description 'Installs/Configures testusers'
version '0.1.0'
