name 'homeusers'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures homeusers'
long_description 'Installs/Configures homeusers'
version '0.1.0'
