name 'linuxusers'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures linuxusers'
long_description 'Installs/Configures linuxusers'
version '0.1.0'
