name 'test_httpd'
maintainer 'Kurt Wallander'
maintainer_email 'kurt.wallander@aol.com'
license 'all_rights'
description 'Installs/Configures test_httpd'
long_description 'Installs/Configures test_httpd'
version '0.1.0'
